Match-id-562e02c2df23943efd114a1ad23fc16d580f546a

diff --git a/ops/BertSelfAttention/cmake.patch b/ops/BertSelfAttention/cmake.patch
--- a/ops/BertSelfAttention/cmake.patch
+++ b/ops/BertSelfAttention/cmake.patch
@@ -1,33 +1,109 @@
-175,179d174
-<   --nox11                           Do not spawn an xterm
-<   --noexec                          Do not run embedded script
-<   --extract=<path>                  Extract directly to a target directory (absolute or relative)
-<                                     Usually used with --noexec to just extract files without running
-<   --tar arg1 [arg2 ...]             Access the contents of the archive through the tar command
-409,419d403
-< 	--tar)
-< 	offset=\`head -n "\$skip" "\$0" | wc -c | tr -d " "\`
-< 	arg1="\$2"
-<     shift 2 || { MS_Help; exit 1; }
-< 	for s in \$filesizes
-< 	do
-< 	    MS_dd "\$0" \$offset \$s | MS_Decompress | tar "\$arg1" - "\$@"
-< 	    offset=\`expr \$offset + \$s\`
-< 	done
-< 	exit 0
-< 	;;
-424,437d407
-< 	;;
-< 	--noexec)
-< 	script=""
-<     cleanup_script=""
-< 	shift
-< 	;;
-<     --extract=*)
-< 	keep=y
-< 	targetdir=\`echo \$1 | cut -d"=" -f2 \`
-<     if ! shift; then MS_Help; exit 1; fi
-< 	;;
-<     --nox11)
-< 	nox11=y
-< 	shift
+--- makeself-header_origin.sh	2024-07-25 23:04:33.000000000 -0400
++++ makeself-header.sh	2024-07-25 23:00:20.000000000 -0400
+@@ -3,12 +3,10 @@
+ # This script was generated using Makeself $MS_VERSION
+ # The license covering this archive and its contents, if any, is wholly independent of the Makeself license (GPL)
+ # 2022.3.19-Modified the MS_Help function and some options
+-# Huawei Technologies Co., Ltd. <foss@huawei.com>
++# Huawei Technologies Co., Ltd.
+ 
+ ORIG_UMASK=\`umask\`
+ 
+-CRCsum="$CRCsum"
+-MD5="$MD5sum"
+ SHA="$SHAsum"
+ SIGNATURE="$Signature"
+ TMPROOT=\${TMPDIR:="\$HOME"}
+@@ -172,11 +170,6 @@
+   --list                            Print the list of files in the archive
+   --check                           Checks integrity and version dependency of the archive
+   --quiet                           Quiet install mode, skip human-computer interactions
+-  --nox11                           Do not spawn an xterm
+-  --noexec                          Do not run embedded script
+-  --extract=<path>                  Extract directly to a target directory (absolute or relative)
+-                                    Usually used with --noexec to just extract files without running
+-  --tar arg1 [arg2 ...]             Access the contents of the archive through the tar command
+ \${helpheader}
+ EOH
+ }
+@@ -232,7 +225,6 @@
+     i=1
+     for s in \$filesizes
+     do
+-		crc=\`echo \$CRCsum | cut -d" " -f\$i\`
+ 		if test -x "\$SHA_PATH"; then
+ 			if test x"\`basename \$SHA_PATH\`" = xshasum; then
+ 				SHA_ARG="-a 256"
+@@ -251,35 +243,6 @@
+ 				crc="0000000000";
+ 			fi
+ 		fi
+-		if test -x "\$MD5_PATH"; then
+-			if test x"\`basename \$MD5_PATH\`" = xdigest; then
+-				MD5_ARG="-a md5"
+-			fi
+-			md5=\`echo \$MD5 | cut -d" " -f\$i\`
+-			if test x"\$md5" = x00000000000000000000000000000000; then
+-				test x"\$verb" = xy && echo " \$1 does not contain an embedded MD5 checksum." >&2
+-			else
+-				md5sum=\`MS_dd_Progress "\$1" \$offset \$s | eval "\$MD5_PATH \$MD5_ARG" | cut -b-32\`;
+-				if test x"\$md5sum" != x"\$md5"; then
+-					echo "Error in MD5 checksums: \$md5sum is different from \$md5" >&2
+-					exit 2
+-				elif test x"\$quiet" = xn; then
+-					MS_Printf " MD5 checksums are OK." >&2
+-				fi
+-				crc="0000000000"; verb=n
+-			fi
+-		fi
+-		if test x"\$crc" = x0000000000; then
+-			test x"\$verb" = xy && echo " \$1 does not contain a CRC checksum." >&2
+-		else
+-			sum1=\`MS_dd_Progress "\$1" \$offset \$s | CMD_ENV=xpg4 cksum | awk '{print \$1}'\`
+-			if test x"\$sum1" != x"\$crc"; then
+-				echo "Error in checksums: \$sum1 is different from \$crc" >&2
+-				exit 2
+-			elif test x"\$quiet" = xn; then
+-				MS_Printf " CRC checksums are OK." >&2
+-			fi
+-		fi
+ 		i=\`expr \$i + 1\`
+ 		offset=\`expr \$offset + \$s\`
+     done
+@@ -406,36 +369,11 @@
+ 	done
+ 	exit 0
+ 	;;
+-	--tar)
+-	offset=\`head -n "\$skip" "\$0" | wc -c | tr -d " "\`
+-	arg1="\$2"
+-    shift 2 || { MS_Help; exit 1; }
+-	for s in \$filesizes
+-	do
+-	    MS_dd "\$0" \$offset \$s | MS_Decompress | tar "\$arg1" - "\$@"
+-	    offset=\`expr \$offset + \$s\`
+-	done
+-	exit 0
+-	;;
+     --check)
+ 	MS_Check "\$0" y
+ 	scriptargs="\$scriptargs \$1"
+     shift
+ 	;;
+-	--noexec)
+-	script=""
+-    cleanup_script=""
+-	shift
+-	;;
+-    --extract=*)
+-	keep=y
+-	targetdir=\`echo \$1 | cut -d"=" -f2 \`
+-    if ! shift; then MS_Help; exit 1; fi
+-	;;
+-    --nox11)
+-	nox11=y
+-	shift
+-	;;
+     --xwin)
+ 	if test "$NOWAIT" = n; then
+ 		finish="echo Press Return to close this window...; read junk"
